/**
 * !! DO NOT EDIT THIS FILE !!
 * このファイルは自動生成されています。直接編集しないでください。
 */

import {serviceFunction} from '../../utils/service-function.js';

/**
 * Hello アクションの例
 * @param {Object} input
 * @param {string} input.name - 名前
 * @returns {Promise<{message: string}>}
 */
export async function hello(input) {
	return serviceFunction.post({
		action: 'hello',
		payload: input,
	});
}
